config/routes.rb
Rails.application.routes.draw do
  resources :violations
  resources :drivers
  root to: "drivers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  validates :name, :points, :age, :picture_url, :presence => true
end

app/models/violation.rb
class Violation < ApplicationRecord
  belongs_to :driver
  validates :driver, :violation_type, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/dmn_model.rb
require 'httparty'

class DmnModel
  class << self
    def execute(violation)
      resp = HTTParty.post(
        'http://0.0.0.0:8080/traffic-violation',
        body: to_dmn(violation).to_json,
        headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
        basic_auth: { username: 'kieserver', password: 'kieserver1!' }).to_h
      resp.to_h
    end

    private

    def to_dmn(violation)
      driver = violation.driver
      {
        'Driver': {
          'Name': driver.name,
          'Points': driver.points,
          'Age': driver.age,
        },
        'Violation': {
          'Type': violation.violation_type,
          'Speed Limit': violation.speed_limit,
          'Actual Speed': violation.actual_speed,
        },
      }
    end
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_driver
    @driver = Driver.find(params[:id])
  end

  def driver_params
    params.require(:driver).permit(:name, :points, :age, :picture_url)
  end
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController
  before_action :set_violation, only: [:show, :edit, :update, :destroy]
  before_action :set_drivers, only: [:new, :edit, :create, :update]

  def index
    @violations = Violation.all
  end

  def new
    @violation = Violation.new
  end

  def create
    @violation = Violation.new(violation_params)

    respond_to do |format|
      if @violation.save

        result = DmnModel.execute(@violation)
        driver = @violation.driver
        driver.points += result['Fine']['Points']
        driver.suspended = result['Should be suspended?'] == 'YES'
        driver.save!

        format.html { redirect_to @violation, notice: 'Violation was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @violation.update(violation_params)
        format.html { redirect_to @violation, notice: 'Violation was successfully updated.' }
        format.json { render :show, status: :ok, location: @violation }
      else
        format.html { render :edit }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @violation.destroy
    respond_to do |format|
      format.html { redirect_to violations_url, notice: 'Violation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_violation
    @violation = Violation.find(params[:id])
  end

  def violation_params
    params.require(:violation).permit(:driver_id, :violation_type, :speed_limit, :actual_speed)
  end

  def set_drivers
    @drivers = Driver.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/violations_helper.rb
module ViolationsHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h2>Editing Driver</h2>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Drivers</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
      <th>Age</th>
      <th>Suspended?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.points %></td>
        <td><%= driver.age %></td>
        <td><%= driver.suspended? %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h2>New Driver</h2>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @driver.name %> (<%= @driver.age %> years old) - <%= @driver.points %> poitns
</p>

<p>
  <%= image_tag @driver.picture_url, class: 'driver-picture' %>
</p>


<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrafficViolation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@700&display=block" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= image_tag("logo.png") %>
      <h1>Traffic Violation</h1>
      -
      <%= link_to 'Drivers', drivers_path %>
      -
      <%= link_to 'Violations', violations_path %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/violations/_form.html.erb
<%= form_with(model: violation, local: true) do |form| %>
  <% if violation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(violation.errors.count, "error") %> prohibited this violation from being saved:</h2>

      <ul>
        <% violation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :driver %>
    <%= form.select(:driver_id, @drivers.map { |d| [d.name, d.id] }, :include_blank => '- Please select the driver -') %>
  </div>

  <div class="field">
    <%= form.label :violation_type %>
    <%= form.text_field :violation_type %>
  </div>

  <div class="field">
    <%= form.label :speed_limit %>
    <%= form.text_field :speed_limit %>
  </div>

  <div class="field">
    <%= form.label :actual_speed %>
    <%= form.text_field :actual_speed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/violations/edit.html.erb
<h2>Editing Violation</h2>

<%= render 'form', violation: @violation %>

<%= link_to 'Show', @violation %> |
<%= link_to 'Back', violations_path %>

app/views/violations/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Violations</h2>

<table>
  <thead>
    <tr>
      <th>Driver</th>
      <th>Type</th>
      <th>Speed limit</th>
      <th>Actual speed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @violations.each do |violation| %>
      <tr>
        <td><%= violation.driver.name %></td>
        <td><%= violation.violation_type %></td>
        <td><%= violation.speed_limit %></td>
        <td><%= violation.actual_speed %></td>
        <td><%= link_to 'Show', violation %></td>
        <td><%= link_to 'Edit', edit_violation_path(violation) %></td>
        <td><%= link_to 'Destroy', violation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Violation', new_violation_path %>

app/views/violations/new.html.erb
<h2>New Violation</h2>

<%= render 'form', violation: @violation %>

<%= link_to 'Back', violations_path %>

app/views/violations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @violation.violation_type %>
</p>

<p>
  <strong>Speed limit:</strong>
  <%= @violation.speed_limit %>
</p>

<p>
  <strong>Actual speed:</strong>
  <%= @violation.actual_speed %>
</p>

<%= link_to 'Edit', edit_violation_path(@violation) %> |
<%= link_to 'Back', violations_path %>